Ext.namespace('Ext.Hudongsoft');

Ext.Hudongsoft.ydglGrid=Ext.extend(Ext.grid.GridPanel ,{
xtype:"grid",
	title:"预定管理",
	store:new Ext.data.JsonStore({
	    autoLoad:true,
		url: 'ydgl.aspx?action=load_data',
		fields:[
		    'id','编码','预定客户名称','所属工业园','所属房产','预定时间','操作时间s'
		]
	
	}),	
	width:792,
	height:560,
	columns:[
		{
			header:"编号",
			sortable:true,
			resizable:true,
			dataIndex:"id",
			width:100
		},
		{
			header:"编码",
			sortable:true,
			resizable:true,
			dataIndex:"编码",
			width:100
		},
		{
			header:"预定客户名称",
			sortable:true,
			resizable:true,
			dataIndex:"预定客户名称",
			width:100
		},
		{
			header:"所属工业园",
			sortable:true,
			resizable:true,
			dataIndex:"所属工业园",
			width:100
		},
		{
			header:"所属房产",
			sortable:true,
			resizable:true,
			dataIndex:"所属房产",
			width:100
		},
		{
			header:"预定时间",
			sortable:true,
			resizable:true,
			dataIndex:"预定时间",
			width:100
		},
		{
			header:"操作时间",
			sortable:true,
			resizable:true,
			dataIndex:"操作时间",
			width:100,
			format:"m/d/Y"
		}
	],
	initComponent: function(){
		this.tbar=[
			{
				text:"新增"
			},
			{
				text:"修改"
			},
			{
				text:"删除"
			},
			{
				xtype:"label",
				text:""
			},
			{
				xtype:"textfield",
				fieldLabel:"标签"
			},
			{
				text:"搜索"
			}
		]
		Ext.Hudongsoft.ydglGrid.superclass.initComponent.call(this);
	}
})