Ext.MyGrid=Ext.extend(Ext.grid.GridPanel ,{
xtype:"grid",
	title:"工业园管理列表",
	store:{
		xtype:"jsonstore",
		autoLoad:true
	},
	width:778,
	height:544,
	columns:[
		{
			header:"编号",
			sortable:true,
			resizable:true,
			dataIndex:"data1",
			width:100
		},
		{
			header:"工业园名称",
			sortable:true,
			resizable:true,
			dataIndex:"data2",
			width:100
		},
		{
			header:"工业面积（平方米）",
			sortable:true,
			resizable:true,
			dataIndex:"data3",
			width:120
		}
	],
	initComponent: function(){
		this.tbar=[
			{
				text:"添加工业园"
			},
			{
				text:"修改工业园"
			},
			{
				text:"删除工业园"
			},
			{
				text:"编辑房产类型"
			}
		]
		Ext.MyGrid.superclass.initComponent.call(this);
	}
})