Ext.MyGrid=Ext.extend(Ext.grid.GridPanel ,{
xtype:"grid",
	title:"自然人列表",
	store:{
		xtype:"jsonstore",
		autoLoad:true
	},
	width:792,
	height:560,
	columns:[
		{
			header:"序号",
			sortable:true,
			resizable:true,
			dataIndex:"data1",
			width:100
		},
		{
			header:"编码",
			sortable:true,
			resizable:true,
			dataIndex:"data2",
			width:100
		},
		{
			header:"名称",
			sortable:true,
			resizable:true,
			dataIndex:"data3",
			width:100
		},
		{
			header:"描述",
			sortable:true,
			resizable:true,
			dataIndex:"",
			width:100
		},
		{
			header:"联系人",
			sortable:true,
			resizable:true,
			dataIndex:"",
			width:100
		},
		{
			header:"联系电话",
			sortable:true,
			resizable:true,
			dataIndex:"",
			width:100
		}
	],
	initComponent: function(){
		this.tbar=[
			{
				text:"新增"
			},
			{
				text:"修改"
			},
			{
				text:"删除"
			},
			{
				xtype:"label",
				text:"姓名："
			},
			{
				xtype:"textfield",
				fieldLabel:"标签"
			},
			{
				text:"搜索"
			}
		]
		Ext.MyGrid.superclass.initComponent.call(this);
	}
})