Ext.namespace('Ext.Hudongsoft');

Ext.Hudongsoft.zrrlbGrid=Ext.extend(Ext.grid.GridPanel ,{
xtype:"grid",
	title:"自然人列表",
		store:new Ext.data.JsonStore({
		autoLoad:true,
		url: 'zrrlb.aspx?action=load_data',
		fields:[
		    'id','编码','名称','描述','联系人','联系电话'
		]
	}),
	width:792,
	height:560,
	columns:[
		{
			header:"序号",
			sortable:true,
			resizable:true,
			dataIndex:"id",
			width:100
		},
		{
			header:"编码",
			sortable:true,
			resizable:true,
			dataIndex:"编码",
			width:100
		},
		{
			header:"名称",
			sortable:true,
			resizable:true,
			dataIndex:"名称",
			width:100
		},
		{
			header:"描述",
			sortable:true,
			resizable:true,
			dataIndex:"描述",
			width:100
		},
		{
			header:"联系人",
			sortable:true,
			resizable:true,
			dataIndex:"联系人",
			width:100
		},
		{
			header:"联系电话",
			sortable:true,
			resizable:true,
			dataIndex:"联系电话",
			width:100
		}
	],
	initComponent: function(){
		this.tbar=[
			{
				text:"新增"
			},
			{
				text:"修改"
			},
			{
				text:"删除"
			},
			{
				xtype:"label",
				text:"姓名："
			},
			{
				xtype:"textfield",
				fieldLabel:"标签"
			},
			{
				text:"搜索"
			}
		]
		Ext.Hudongsoft.zrrlbGrid.superclass.initComponent.call(this);
	}
})