//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行库版本:2.0.50727.1433
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Microsoft.Samples.SqlServer.Properties {
    using System;
    
    
    /// <summary>
    ///   强类型资源类，用于查找本地化字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Microsoft.Samples.SqlServer.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   为使用此强类型资源类的所有资源查找
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 数据同步监视器用来监视数据同步信息和状态。
        /// 的本地化字符串。
        /// </summary>
        internal static string AboutDescription {
            get {
                return ResourceManager.GetString("AboutDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 互动科技版权所有 的本地化字符串。
        /// </summary>
        internal static string AboutDisclaimer {
            get {
                return ResourceManager.GetString("AboutDisclaimer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似     项目:  的本地化字符串。
        /// </summary>
        internal static string ArticleName {
            get {
                return ResourceManager.GetString("ArticleName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 完成  的本地化字符串。
        /// </summary>
        internal static string Completed {
            get {
                return ResourceManager.GetString("Completed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 最后更新:  的本地化字符串。
        /// </summary>
        internal static string LastRefresh {
            get {
                return ResourceManager.GetString("LastRefresh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 上次成功同步:  的本地化字符串。
        /// </summary>
        internal static string LastSync {
            get {
                return ResourceManager.GetString("LastSync", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 合并会话 的本地化字符串。
        /// </summary>
        internal static string MergeSessions {
            get {
                return ResourceManager.GetString("MergeSessions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 订阅同步未成功 的本地化字符串。
        /// </summary>
        internal static string NoSuccessSyncs {
            get {
                return ResourceManager.GetString("NoSuccessSyncs", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap SubSideMonitoringUI_ConnectDlg {
            get {
                object obj = ResourceManager.GetObject("SubSideMonitoringUI_ConnectDlg", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
