//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行库版本:2.0.50727.1433
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

// 
// 此源代码是由 Microsoft.VSDesigner 2.0.50727.1433 版自动生成。
// 
#pragma warning disable 1591

namespace LiveSupport.OperatorConsole.LiveChatWS {
    using System.Diagnostics;
    using System.Web.Services;
    using System.ComponentModel;
    using System.Web.Services.Protocols;
    using System;
    using System.Xml.Serialization;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.1433")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="OperatorWSSoap", Namespace="http://www.LiveSupport.cn/LiveSupportService/2009/04")]
    public partial class OperatorWS : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private AuthenticationHeader authenticationHeaderValueField;
        
        private System.Threading.SendOrPostCallback LoginOperationCompleted;
        
        private System.Threading.SendOrPostCallback LogoutOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetAllVisitorsOperationCompleted;
        
        private System.Threading.SendOrPostCallback CheckNewChangesOperationCompleted;
        
        private System.Threading.SendOrPostCallback IsTypingOperationCompleted;
        
        private System.Threading.SendOrPostCallback SendFileOperationCompleted;
        
        private System.Threading.SendOrPostCallback UploadFileOperationCompleted;
        
        private System.Threading.SendOrPostCallback SendMessageOperationCompleted;
        
        private System.Threading.SendOrPostCallback ChangePasswordOperationCompleted;
        
        private System.Threading.SendOrPostCallback ResetOperatorPasswordOperationCompleted;
        
        private System.Threading.SendOrPostCallback CloseChatOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetHistoryChatMessageOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetHistoryPageRequestsOperationCompleted;
        
        private System.Threading.SendOrPostCallback AcceptChatRequestOperationCompleted;
        
        private System.Threading.SendOrPostCallback InviteChatOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetSystemAdvertiseOperationCompleted;
        
        private System.Threading.SendOrPostCallback SaveQuickResponseOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetQuickResponseOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public OperatorWS() {
            this.Url = global::LiveSupport.OperatorConsole.Properties.Settings.Default.OperatorConsole_LiveChatWS_Operator;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public AuthenticationHeader AuthenticationHeaderValue {
            get {
                return this.authenticationHeaderValueField;
            }
            set {
                this.authenticationHeaderValueField = value;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event LoginCompletedEventHandler LoginCompleted;
        
        /// <remarks/>
        public event LogoutCompletedEventHandler LogoutCompleted;
        
        /// <remarks/>
        public event GetAllVisitorsCompletedEventHandler GetAllVisitorsCompleted;
        
        /// <remarks/>
        public event CheckNewChangesCompletedEventHandler CheckNewChangesCompleted;
        
        /// <remarks/>
        public event IsTypingCompletedEventHandler IsTypingCompleted;
        
        /// <remarks/>
        public event SendFileCompletedEventHandler SendFileCompleted;
        
        /// <remarks/>
        public event UploadFileCompletedEventHandler UploadFileCompleted;
        
        /// <remarks/>
        public event SendMessageCompletedEventHandler SendMessageCompleted;
        
        /// <remarks/>
        public event ChangePasswordCompletedEventHandler ChangePasswordCompleted;
        
        /// <remarks/>
        public event ResetOperatorPasswordCompletedEventHandler ResetOperatorPasswordCompleted;
        
        /// <remarks/>
        public event CloseChatCompletedEventHandler CloseChatCompleted;
        
        /// <remarks/>
        public event GetHistoryChatMessageCompletedEventHandler GetHistoryChatMessageCompleted;
        
        /// <remarks/>
        public event GetHistoryPageRequestsCompletedEventHandler GetHistoryPageRequestsCompleted;
        
        /// <remarks/>
        public event AcceptChatRequestCompletedEventHandler AcceptChatRequestCompleted;
        
        /// <remarks/>
        public event InviteChatCompletedEventHandler InviteChatCompleted;
        
        /// <remarks/>
        public event GetSystemAdvertiseCompletedEventHandler GetSystemAdvertiseCompleted;
        
        /// <remarks/>
        public event SaveQuickResponseCompletedEventHandler SaveQuickResponseCompleted;
        
        /// <remarks/>
        public event GetQuickResponseCompletedEventHandler GetQuickResponseCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("AuthenticationHeaderValue")]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.LiveSupport.cn/LiveSupportService/2009/04/Login", RequestNamespace="http://www.LiveSupport.cn/LiveSupportService/2009/04", ResponseNamespace="http://www.LiveSupport.cn/LiveSupportService/2009/04", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public Operator Login(string accountNumber, string operatorName, string password) {
            object[] results = this.Invoke("Login", new object[] {
                        accountNumber,
                        operatorName,
                        password});
            return ((Operator)(results[0]));
        }
        
        /// <remarks/>
        public void LoginAsync(string accountNumber, string operatorName, string password) {
            this.LoginAsync(accountNumber, operatorName, password, null);
        }
        
        /// <remarks/>
        public void LoginAsync(string accountNumber, string operatorName, string password, object userState) {
            if ((this.LoginOperationCompleted == null)) {
                this.LoginOperationCompleted = new System.Threading.SendOrPostCallback(this.OnLoginOperationCompleted);
            }
            this.InvokeAsync("Login", new object[] {
                        accountNumber,
                        operatorName,
                        password}, this.LoginOperationCompleted, userState);
        }
        
        private void OnLoginOperationCompleted(object arg) {
            if ((this.LoginCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.LoginCompleted(this, new LoginCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("AuthenticationHeaderValue")]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.LiveSupport.cn/LiveSupportService/2009/04/Logout", RequestNamespace="http://www.LiveSupport.cn/LiveSupportService/2009/04", ResponseNamespace="http://www.LiveSupport.cn/LiveSupportService/2009/04", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void Logout() {
            this.Invoke("Logout", new object[0]);
        }
        
        /// <remarks/>
        public void LogoutAsync() {
            this.LogoutAsync(null);
        }
        
        /// <remarks/>
        public void LogoutAsync(object userState) {
            if ((this.LogoutOperationCompleted == null)) {
                this.LogoutOperationCompleted = new System.Threading.SendOrPostCallback(this.OnLogoutOperationCompleted);
            }
            this.InvokeAsync("Logout", new object[0], this.LogoutOperationCompleted, userState);
        }
        
        private void OnLogoutOperationCompleted(object arg) {
            if ((this.LogoutCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.LogoutCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("AuthenticationHeaderValue")]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.LiveSupport.cn/LiveSupportService/2009/04/GetAllVisitors", RequestNamespace="http://www.LiveSupport.cn/LiveSupportService/2009/04", ResponseNamespace="http://www.LiveSupport.cn/LiveSupportService/2009/04", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public Visitor[] GetAllVisitors(string accountId) {
            object[] results = this.Invoke("GetAllVisitors", new object[] {
                        accountId});
            return ((Visitor[])(results[0]));
        }
        
        /// <remarks/>
        public void GetAllVisitorsAsync(string accountId) {
            this.GetAllVisitorsAsync(accountId, null);
        }
        
        /// <remarks/>
        public void GetAllVisitorsAsync(string accountId, object userState) {
            if ((this.GetAllVisitorsOperationCompleted == null)) {
                this.GetAllVisitorsOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetAllVisitorsOperationCompleted);
            }
            this.InvokeAsync("GetAllVisitors", new object[] {
                        accountId}, this.GetAllVisitorsOperationCompleted, userState);
        }
        
        private void OnGetAllVisitorsOperationCompleted(object arg) {
            if ((this.GetAllVisitorsCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetAllVisitorsCompleted(this, new GetAllVisitorsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("AuthenticationHeaderValue")]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.LiveSupport.cn/LiveSupportService/2009/04/CheckNewChanges", RequestNamespace="http://www.LiveSupport.cn/LiveSupportService/2009/04", ResponseNamespace="http://www.LiveSupport.cn/LiveSupportService/2009/04", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public NewChangesCheckResult CheckNewChanges(NewChangesCheck check) {
            object[] results = this.Invoke("CheckNewChanges", new object[] {
                        check});
            return ((NewChangesCheckResult)(results[0]));
        }
        
        /// <remarks/>
        public void CheckNewChangesAsync(NewChangesCheck check) {
            this.CheckNewChangesAsync(check, null);
        }
        
        /// <remarks/>
        public void CheckNewChangesAsync(NewChangesCheck check, object userState) {
            if ((this.CheckNewChangesOperationCompleted == null)) {
                this.CheckNewChangesOperationCompleted = new System.Threading.SendOrPostCallback(this.OnCheckNewChangesOperationCompleted);
            }
            this.InvokeAsync("CheckNewChanges", new object[] {
                        check}, this.CheckNewChangesOperationCompleted, userState);
        }
        
        private void OnCheckNewChangesOperationCompleted(object arg) {
            if ((this.CheckNewChangesCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.CheckNewChangesCompleted(this, new CheckNewChangesCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("AuthenticationHeaderValue")]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.LiveSupport.cn/LiveSupportService/2009/04/IsTyping", RequestNamespace="http://www.LiveSupport.cn/LiveSupportService/2009/04", ResponseNamespace="http://www.LiveSupport.cn/LiveSupportService/2009/04", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool IsTyping(string chatId, bool isOperator) {
            object[] results = this.Invoke("IsTyping", new object[] {
                        chatId,
                        isOperator});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void IsTypingAsync(string chatId, bool isOperator) {
            this.IsTypingAsync(chatId, isOperator, null);
        }
        
        /// <remarks/>
        public void IsTypingAsync(string chatId, bool isOperator, object userState) {
            if ((this.IsTypingOperationCompleted == null)) {
                this.IsTypingOperationCompleted = new System.Threading.SendOrPostCallback(this.OnIsTypingOperationCompleted);
            }
            this.InvokeAsync("IsTyping", new object[] {
                        chatId,
                        isOperator}, this.IsTypingOperationCompleted, userState);
        }
        
        private void OnIsTypingOperationCompleted(object arg) {
            if ((this.IsTypingCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.IsTypingCompleted(this, new IsTypingCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("AuthenticationHeaderValue")]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.LiveSupport.cn/LiveSupportService/2009/04/SendFile", RequestNamespace="http://www.LiveSupport.cn/LiveSupportService/2009/04", ResponseNamespace="http://www.LiveSupport.cn/LiveSupportService/2009/04", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void SendFile(string fileName, string chatId, object action) {
            this.Invoke("SendFile", new object[] {
                        fileName,
                        chatId,
                        action});
        }
        
        /// <remarks/>
        public void SendFileAsync(string fileName, string chatId, object action) {
            this.SendFileAsync(fileName, chatId, action, null);
        }
        
        /// <remarks/>
        public void SendFileAsync(string fileName, string chatId, object action, object userState) {
            if ((this.SendFileOperationCompleted == null)) {
                this.SendFileOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSendFileOperationCompleted);
            }
            this.InvokeAsync("SendFile", new object[] {
                        fileName,
                        chatId,
                        action}, this.SendFileOperationCompleted, userState);
        }
        
        private void OnSendFileOperationCompleted(object arg) {
            if ((this.SendFileCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.SendFileCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("AuthenticationHeaderValue")]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.LiveSupport.cn/LiveSupportService/2009/04/UploadFile", RequestNamespace="http://www.LiveSupport.cn/LiveSupportService/2009/04", ResponseNamespace="http://www.LiveSupport.cn/LiveSupportService/2009/04", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void UploadFile([System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary")] byte[] bs, string fileName, string chatId) {
            this.Invoke("UploadFile", new object[] {
                        bs,
                        fileName,
                        chatId});
        }
        
        /// <remarks/>
        public void UploadFileAsync(byte[] bs, string fileName, string chatId) {
            this.UploadFileAsync(bs, fileName, chatId, null);
        }
        
        /// <remarks/>
        public void UploadFileAsync(byte[] bs, string fileName, string chatId, object userState) {
            if ((this.UploadFileOperationCompleted == null)) {
                this.UploadFileOperationCompleted = new System.Threading.SendOrPostCallback(this.OnUploadFileOperationCompleted);
            }
            this.InvokeAsync("UploadFile", new object[] {
                        bs,
                        fileName,
                        chatId}, this.UploadFileOperationCompleted, userState);
        }
        
        private void OnUploadFileOperationCompleted(object arg) {
            if ((this.UploadFileCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.UploadFileCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("AuthenticationHeaderValue")]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.LiveSupport.cn/LiveSupportService/2009/04/SendMessage", RequestNamespace="http://www.LiveSupport.cn/LiveSupportService/2009/04", ResponseNamespace="http://www.LiveSupport.cn/LiveSupportService/2009/04", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool SendMessage(Message msg) {
            object[] results = this.Invoke("SendMessage", new object[] {
                        msg});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void SendMessageAsync(Message msg) {
            this.SendMessageAsync(msg, null);
        }
        
        /// <remarks/>
        public void SendMessageAsync(Message msg, object userState) {
            if ((this.SendMessageOperationCompleted == null)) {
                this.SendMessageOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSendMessageOperationCompleted);
            }
            this.InvokeAsync("SendMessage", new object[] {
                        msg}, this.SendMessageOperationCompleted, userState);
        }
        
        private void OnSendMessageOperationCompleted(object arg) {
            if ((this.SendMessageCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.SendMessageCompleted(this, new SendMessageCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("AuthenticationHeaderValue")]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.LiveSupport.cn/LiveSupportService/2009/04/ChangePassword", RequestNamespace="http://www.LiveSupport.cn/LiveSupportService/2009/04", ResponseNamespace="http://www.LiveSupport.cn/LiveSupportService/2009/04", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public int ChangePassword(string oldPassword, string newPassword) {
            object[] results = this.Invoke("ChangePassword", new object[] {
                        oldPassword,
                        newPassword});
            return ((int)(results[0]));
        }
        
        /// <remarks/>
        public void ChangePasswordAsync(string oldPassword, string newPassword) {
            this.ChangePasswordAsync(oldPassword, newPassword, null);
        }
        
        /// <remarks/>
        public void ChangePasswordAsync(string oldPassword, string newPassword, object userState) {
            if ((this.ChangePasswordOperationCompleted == null)) {
                this.ChangePasswordOperationCompleted = new System.Threading.SendOrPostCallback(this.OnChangePasswordOperationCompleted);
            }
            this.InvokeAsync("ChangePassword", new object[] {
                        oldPassword,
                        newPassword}, this.ChangePasswordOperationCompleted, userState);
        }
        
        private void OnChangePasswordOperationCompleted(object arg) {
            if ((this.ChangePasswordCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ChangePasswordCompleted(this, new ChangePasswordCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("AuthenticationHeaderValue")]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.LiveSupport.cn/LiveSupportService/2009/04/ResetOperatorPassword", RequestNamespace="http://www.LiveSupport.cn/LiveSupportService/2009/04", ResponseNamespace="http://www.LiveSupport.cn/LiveSupportService/2009/04", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public int ResetOperatorPassword(string loginName) {
            object[] results = this.Invoke("ResetOperatorPassword", new object[] {
                        loginName});
            return ((int)(results[0]));
        }
        
        /// <remarks/>
        public void ResetOperatorPasswordAsync(string loginName) {
            this.ResetOperatorPasswordAsync(loginName, null);
        }
        
        /// <remarks/>
        public void ResetOperatorPasswordAsync(string loginName, object userState) {
            if ((this.ResetOperatorPasswordOperationCompleted == null)) {
                this.ResetOperatorPasswordOperationCompleted = new System.Threading.SendOrPostCallback(this.OnResetOperatorPasswordOperationCompleted);
            }
            this.InvokeAsync("ResetOperatorPassword", new object[] {
                        loginName}, this.ResetOperatorPasswordOperationCompleted, userState);
        }
        
        private void OnResetOperatorPasswordOperationCompleted(object arg) {
            if ((this.ResetOperatorPasswordCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ResetOperatorPasswordCompleted(this, new ResetOperatorPasswordCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("AuthenticationHeaderValue")]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.LiveSupport.cn/LiveSupportService/2009/04/CloseChat", RequestNamespace="http://www.LiveSupport.cn/LiveSupportService/2009/04", ResponseNamespace="http://www.LiveSupport.cn/LiveSupportService/2009/04", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool CloseChat(string chatId) {
            object[] results = this.Invoke("CloseChat", new object[] {
                        chatId});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void CloseChatAsync(string chatId) {
            this.CloseChatAsync(chatId, null);
        }
        
        /// <remarks/>
        public void CloseChatAsync(string chatId, object userState) {
            if ((this.CloseChatOperationCompleted == null)) {
                this.CloseChatOperationCompleted = new System.Threading.SendOrPostCallback(this.OnCloseChatOperationCompleted);
            }
            this.InvokeAsync("CloseChat", new object[] {
                        chatId}, this.CloseChatOperationCompleted, userState);
        }
        
        private void OnCloseChatOperationCompleted(object arg) {
            if ((this.CloseChatCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.CloseChatCompleted(this, new CloseChatCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("AuthenticationHeaderValue")]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.LiveSupport.cn/LiveSupportService/2009/04/GetHistoryChatMessage", RequestNamespace="http://www.LiveSupport.cn/LiveSupportService/2009/04", ResponseNamespace="http://www.LiveSupport.cn/LiveSupportService/2009/04", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public Message[] GetHistoryChatMessage(string visitorId, System.DateTime begin, System.DateTime end) {
            object[] results = this.Invoke("GetHistoryChatMessage", new object[] {
                        visitorId,
                        begin,
                        end});
            return ((Message[])(results[0]));
        }
        
        /// <remarks/>
        public void GetHistoryChatMessageAsync(string visitorId, System.DateTime begin, System.DateTime end) {
            this.GetHistoryChatMessageAsync(visitorId, begin, end, null);
        }
        
        /// <remarks/>
        public void GetHistoryChatMessageAsync(string visitorId, System.DateTime begin, System.DateTime end, object userState) {
            if ((this.GetHistoryChatMessageOperationCompleted == null)) {
                this.GetHistoryChatMessageOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetHistoryChatMessageOperationCompleted);
            }
            this.InvokeAsync("GetHistoryChatMessage", new object[] {
                        visitorId,
                        begin,
                        end}, this.GetHistoryChatMessageOperationCompleted, userState);
        }
        
        private void OnGetHistoryChatMessageOperationCompleted(object arg) {
            if ((this.GetHistoryChatMessageCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetHistoryChatMessageCompleted(this, new GetHistoryChatMessageCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("AuthenticationHeaderValue")]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.LiveSupport.cn/LiveSupportService/2009/04/GetHistoryPageRequests", RequestNamespace="http://www.LiveSupport.cn/LiveSupportService/2009/04", ResponseNamespace="http://www.LiveSupport.cn/LiveSupportService/2009/04", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public PageRequest[] GetHistoryPageRequests(string visitorId, System.DateTime begin, System.DateTime end) {
            object[] results = this.Invoke("GetHistoryPageRequests", new object[] {
                        visitorId,
                        begin,
                        end});
            return ((PageRequest[])(results[0]));
        }
        
        /// <remarks/>
        public void GetHistoryPageRequestsAsync(string visitorId, System.DateTime begin, System.DateTime end) {
            this.GetHistoryPageRequestsAsync(visitorId, begin, end, null);
        }
        
        /// <remarks/>
        public void GetHistoryPageRequestsAsync(string visitorId, System.DateTime begin, System.DateTime end, object userState) {
            if ((this.GetHistoryPageRequestsOperationCompleted == null)) {
                this.GetHistoryPageRequestsOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetHistoryPageRequestsOperationCompleted);
            }
            this.InvokeAsync("GetHistoryPageRequests", new object[] {
                        visitorId,
                        begin,
                        end}, this.GetHistoryPageRequestsOperationCompleted, userState);
        }
        
        private void OnGetHistoryPageRequestsOperationCompleted(object arg) {
            if ((this.GetHistoryPageRequestsCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetHistoryPageRequestsCompleted(this, new GetHistoryPageRequestsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("AuthenticationHeaderValue")]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.LiveSupport.cn/LiveSupportService/2009/04/AcceptChatRequest", RequestNamespace="http://www.LiveSupport.cn/LiveSupportService/2009/04", ResponseNamespace="http://www.LiveSupport.cn/LiveSupportService/2009/04", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public int AcceptChatRequest(string chatId) {
            object[] results = this.Invoke("AcceptChatRequest", new object[] {
                        chatId});
            return ((int)(results[0]));
        }
        
        /// <remarks/>
        public void AcceptChatRequestAsync(string chatId) {
            this.AcceptChatRequestAsync(chatId, null);
        }
        
        /// <remarks/>
        public void AcceptChatRequestAsync(string chatId, object userState) {
            if ((this.AcceptChatRequestOperationCompleted == null)) {
                this.AcceptChatRequestOperationCompleted = new System.Threading.SendOrPostCallback(this.OnAcceptChatRequestOperationCompleted);
            }
            this.InvokeAsync("AcceptChatRequest", new object[] {
                        chatId}, this.AcceptChatRequestOperationCompleted, userState);
        }
        
        private void OnAcceptChatRequestOperationCompleted(object arg) {
            if ((this.AcceptChatRequestCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.AcceptChatRequestCompleted(this, new AcceptChatRequestCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("AuthenticationHeaderValue")]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.LiveSupport.cn/LiveSupportService/2009/04/InviteChat", RequestNamespace="http://www.LiveSupport.cn/LiveSupportService/2009/04", ResponseNamespace="http://www.LiveSupport.cn/LiveSupportService/2009/04", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public Chat InviteChat(string visitorId) {
            object[] results = this.Invoke("InviteChat", new object[] {
                        visitorId});
            return ((Chat)(results[0]));
        }
        
        /// <remarks/>
        public void InviteChatAsync(string visitorId) {
            this.InviteChatAsync(visitorId, null);
        }
        
        /// <remarks/>
        public void InviteChatAsync(string visitorId, object userState) {
            if ((this.InviteChatOperationCompleted == null)) {
                this.InviteChatOperationCompleted = new System.Threading.SendOrPostCallback(this.OnInviteChatOperationCompleted);
            }
            this.InvokeAsync("InviteChat", new object[] {
                        visitorId}, this.InviteChatOperationCompleted, userState);
        }
        
        private void OnInviteChatOperationCompleted(object arg) {
            if ((this.InviteChatCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.InviteChatCompleted(this, new InviteChatCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("AuthenticationHeaderValue")]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.LiveSupport.cn/LiveSupportService/2009/04/GetSystemAdvertise", RequestNamespace="http://www.LiveSupport.cn/LiveSupportService/2009/04", ResponseNamespace="http://www.LiveSupport.cn/LiveSupportService/2009/04", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public SystemAdvertise[] GetSystemAdvertise(string versionNumber) {
            object[] results = this.Invoke("GetSystemAdvertise", new object[] {
                        versionNumber});
            return ((SystemAdvertise[])(results[0]));
        }
        
        /// <remarks/>
        public void GetSystemAdvertiseAsync(string versionNumber) {
            this.GetSystemAdvertiseAsync(versionNumber, null);
        }
        
        /// <remarks/>
        public void GetSystemAdvertiseAsync(string versionNumber, object userState) {
            if ((this.GetSystemAdvertiseOperationCompleted == null)) {
                this.GetSystemAdvertiseOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetSystemAdvertiseOperationCompleted);
            }
            this.InvokeAsync("GetSystemAdvertise", new object[] {
                        versionNumber}, this.GetSystemAdvertiseOperationCompleted, userState);
        }
        
        private void OnGetSystemAdvertiseOperationCompleted(object arg) {
            if ((this.GetSystemAdvertiseCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetSystemAdvertiseCompleted(this, new GetSystemAdvertiseCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("AuthenticationHeaderValue")]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.LiveSupport.cn/LiveSupportService/2009/04/SaveQuickResponse", RequestNamespace="http://www.LiveSupport.cn/LiveSupportService/2009/04", ResponseNamespace="http://www.LiveSupport.cn/LiveSupportService/2009/04", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void SaveQuickResponse(QuickResponseCategory[] response) {
            this.Invoke("SaveQuickResponse", new object[] {
                        response});
        }
        
        /// <remarks/>
        public void SaveQuickResponseAsync(QuickResponseCategory[] response) {
            this.SaveQuickResponseAsync(response, null);
        }
        
        /// <remarks/>
        public void SaveQuickResponseAsync(QuickResponseCategory[] response, object userState) {
            if ((this.SaveQuickResponseOperationCompleted == null)) {
                this.SaveQuickResponseOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSaveQuickResponseOperationCompleted);
            }
            this.InvokeAsync("SaveQuickResponse", new object[] {
                        response}, this.SaveQuickResponseOperationCompleted, userState);
        }
        
        private void OnSaveQuickResponseOperationCompleted(object arg) {
            if ((this.SaveQuickResponseCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.SaveQuickResponseCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("AuthenticationHeaderValue")]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.LiveSupport.cn/LiveSupportService/2009/04/GetQuickResponse", RequestNamespace="http://www.LiveSupport.cn/LiveSupportService/2009/04", ResponseNamespace="http://www.LiveSupport.cn/LiveSupportService/2009/04", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public QuickResponseCategory[] GetQuickResponse() {
            object[] results = this.Invoke("GetQuickResponse", new object[0]);
            return ((QuickResponseCategory[])(results[0]));
        }
        
        /// <remarks/>
        public void GetQuickResponseAsync() {
            this.GetQuickResponseAsync(null);
        }
        
        /// <remarks/>
        public void GetQuickResponseAsync(object userState) {
            if ((this.GetQuickResponseOperationCompleted == null)) {
                this.GetQuickResponseOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetQuickResponseOperationCompleted);
            }
            this.InvokeAsync("GetQuickResponse", new object[0], this.GetQuickResponseOperationCompleted, userState);
        }
        
        private void OnGetQuickResponseOperationCompleted(object arg) {
            if ((this.GetQuickResponseCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetQuickResponseCompleted(this, new GetQuickResponseCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.1433")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.LiveSupport.cn/LiveSupportService/2009/04")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://www.LiveSupport.cn/LiveSupportService/2009/04", IsNullable=false)]
    public partial class AuthenticationHeader : System.Web.Services.Protocols.SoapHeader {
        
        private string operatorIdField;
        
        private string operatorSessionField;
        
        private System.Xml.XmlAttribute[] anyAttrField;
        
        /// <remarks/>
        public string OperatorId {
            get {
                return this.operatorIdField;
            }
            set {
                this.operatorIdField = value;
            }
        }
        
        /// <remarks/>
        public string OperatorSession {
            get {
                return this.operatorSessionField;
            }
            set {
                this.operatorSessionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAnyAttributeAttribute()]
        public System.Xml.XmlAttribute[] AnyAttr {
            get {
                return this.anyAttrField;
            }
            set {
                this.anyAttrField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.1433")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.LiveSupport.cn/LiveSupportService/2009/04")]
    public partial class QuickResponseCategory {
        
        private int quickIdField;
        
        private string nameField;
        
        private string[] responsesField;
        
        /// <remarks/>
        public int QuickId {
            get {
                return this.quickIdField;
            }
            set {
                this.quickIdField = value;
            }
        }
        
        /// <remarks/>
        public string Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        public string[] Responses {
            get {
                return this.responsesField;
            }
            set {
                this.responsesField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.1433")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.LiveSupport.cn/LiveSupportService/2009/04")]
    public partial class SystemAdvertise {
        
        private string advertiseUrlField;
        
        private string advertiseMessageField;
        
        /// <remarks/>
        public string AdvertiseUrl {
            get {
                return this.advertiseUrlField;
            }
            set {
                this.advertiseUrlField = value;
            }
        }
        
        /// <remarks/>
        public string AdvertiseMessage {
            get {
                return this.advertiseMessageField;
            }
            set {
                this.advertiseMessageField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.1433")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.LiveSupport.cn/LiveSupportService/2009/04")]
    public partial class PageRequest {
        
        private string accountIdField;
        
        private string sessionIdField;
        
        private string pageField;
        
        private System.DateTime requestTimeField;
        
        private string referrerField;
        
        /// <remarks/>
        public string AccountId {
            get {
                return this.accountIdField;
            }
            set {
                this.accountIdField = value;
            }
        }
        
        /// <remarks/>
        public string SessionId {
            get {
                return this.sessionIdField;
            }
            set {
                this.sessionIdField = value;
            }
        }
        
        /// <remarks/>
        public string Page {
            get {
                return this.pageField;
            }
            set {
                this.pageField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime RequestTime {
            get {
                return this.requestTimeField;
            }
            set {
                this.requestTimeField = value;
            }
        }
        
        /// <remarks/>
        public string Referrer {
            get {
                return this.referrerField;
            }
            set {
                this.referrerField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.1433")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.LiveSupport.cn/LiveSupportService/2009/04")]
    public partial class Message {
        
        private string messageIdField;
        
        private string chatIdField;
        
        private string sourceField;
        
        private string destinationField;
        
        private string textField;
        
        private System.DateTime sentDateField;
        
        private MessageType typeField;
        
        /// <remarks/>
        public string MessageId {
            get {
                return this.messageIdField;
            }
            set {
                this.messageIdField = value;
            }
        }
        
        /// <remarks/>
        public string ChatId {
            get {
                return this.chatIdField;
            }
            set {
                this.chatIdField = value;
            }
        }
        
        /// <remarks/>
        public string Source {
            get {
                return this.sourceField;
            }
            set {
                this.sourceField = value;
            }
        }
        
        /// <remarks/>
        public string Destination {
            get {
                return this.destinationField;
            }
            set {
                this.destinationField = value;
            }
        }
        
        /// <remarks/>
        public string Text {
            get {
                return this.textField;
            }
            set {
                this.textField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime SentDate {
            get {
                return this.sentDateField;
            }
            set {
                this.sentDateField = value;
            }
        }
        
        /// <remarks/>
        public MessageType Type {
            get {
                return this.typeField;
            }
            set {
                this.typeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.1433")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.LiveSupport.cn/LiveSupportService/2009/04")]
    public enum MessageType {
        
        /// <remarks/>
        ChatMessage_OperatorToVisitor,
        
        /// <remarks/>
        ChatMessage_VistorToOperator,
        
        /// <remarks/>
        SystemMessage_ToOperator,
        
        /// <remarks/>
        SystemMessage_ToVisitor,
        
        /// <remarks/>
        SystemMessage_ToBoth,
        
        /// <remarks/>
        CommandMessage_VidoeChat_OperatorToVisitor,
        
        /// <remarks/>
        CommandMessage_VideoChat_VistorToOperator,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.1433")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.LiveSupport.cn/LiveSupportService/2009/04")]
    public partial class MessageCheckResult {
        
        private string chatIdField;
        
        private Message[] messagesField;
        
        /// <remarks/>
        public string ChatId {
            get {
                return this.chatIdField;
            }
            set {
                this.chatIdField = value;
            }
        }
        
        /// <remarks/>
        public Message[] Messages {
            get {
                return this.messagesField;
            }
            set {
                this.messagesField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.1433")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.LiveSupport.cn/LiveSupportService/2009/04")]
    public partial class Chat {
        
        private string chatIdField;
        
        private string createByField;
        
        private string closeByField;
        
        private System.DateTime createTimeField;
        
        private System.DateTime acceptTimeField;
        
        private System.DateTime closeTimeField;
        
        private string accountIdField;
        
        private string visitorIdField;
        
        private string operatorIdField;
        
        private ChatStatus statusField;
        
        private VisitSession vsField;
        
        private bool isInviteByOperatorField;
        
        private long lastCheckTimeField;
        
        /// <remarks/>
        public string ChatId {
            get {
                return this.chatIdField;
            }
            set {
                this.chatIdField = value;
            }
        }
        
        /// <remarks/>
        public string CreateBy {
            get {
                return this.createByField;
            }
            set {
                this.createByField = value;
            }
        }
        
        /// <remarks/>
        public string CloseBy {
            get {
                return this.closeByField;
            }
            set {
                this.closeByField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime CreateTime {
            get {
                return this.createTimeField;
            }
            set {
                this.createTimeField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime AcceptTime {
            get {
                return this.acceptTimeField;
            }
            set {
                this.acceptTimeField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime CloseTime {
            get {
                return this.closeTimeField;
            }
            set {
                this.closeTimeField = value;
            }
        }
        
        /// <remarks/>
        public string AccountId {
            get {
                return this.accountIdField;
            }
            set {
                this.accountIdField = value;
            }
        }
        
        /// <remarks/>
        public string VisitorId {
            get {
                return this.visitorIdField;
            }
            set {
                this.visitorIdField = value;
            }
        }
        
        /// <remarks/>
        public string OperatorId {
            get {
                return this.operatorIdField;
            }
            set {
                this.operatorIdField = value;
            }
        }
        
        /// <remarks/>
        public ChatStatus Status {
            get {
                return this.statusField;
            }
            set {
                this.statusField = value;
            }
        }
        
        /// <remarks/>
        public VisitSession Vs {
            get {
                return this.vsField;
            }
            set {
                this.vsField = value;
            }
        }
        
        /// <remarks/>
        public bool IsInviteByOperator {
            get {
                return this.isInviteByOperatorField;
            }
            set {
                this.isInviteByOperatorField = value;
            }
        }
        
        /// <remarks/>
        public long LastCheckTime {
            get {
                return this.lastCheckTimeField;
            }
            set {
                this.lastCheckTimeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.1433")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.LiveSupport.cn/LiveSupportService/2009/04")]
    public enum ChatStatus {
        
        /// <remarks/>
        Requested,
        
        /// <remarks/>
        Accepted,
        
        /// <remarks/>
        Decline,
        
        /// <remarks/>
        Closed,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.1433")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.LiveSupport.cn/LiveSupportService/2009/04")]
    public partial class VisitSession {
        
        private string sessionIdField;
        
        private string visitorIdField;
        
        private string ipField;
        
        private string browserField;
        
        private VisitSessionStatus statusField;
        
        private string locationField;
        
        private string operatorIdField;
        
        private System.DateTime visitingTimeField;
        
        private System.DateTime leaveTimeField;
        
        private System.DateTime chatRequestTimeField;
        
        private System.DateTime chatingTimeField;
        
        private System.DateTime waitingDuringField;
        
        private System.DateTime chattingDuringField;
        
        private int pageRequestCountField;
        
        private string domainRequestedField;
        
        private string pageRequestedField;
        
        private string referrerField;
        
        /// <remarks/>
        public string SessionId {
            get {
                return this.sessionIdField;
            }
            set {
                this.sessionIdField = value;
            }
        }
        
        /// <remarks/>
        public string VisitorId {
            get {
                return this.visitorIdField;
            }
            set {
                this.visitorIdField = value;
            }
        }
        
        /// <remarks/>
        public string IP {
            get {
                return this.ipField;
            }
            set {
                this.ipField = value;
            }
        }
        
        /// <remarks/>
        public string Browser {
            get {
                return this.browserField;
            }
            set {
                this.browserField = value;
            }
        }
        
        /// <remarks/>
        public VisitSessionStatus Status {
            get {
                return this.statusField;
            }
            set {
                this.statusField = value;
            }
        }
        
        /// <remarks/>
        public string Location {
            get {
                return this.locationField;
            }
            set {
                this.locationField = value;
            }
        }
        
        /// <remarks/>
        public string OperatorId {
            get {
                return this.operatorIdField;
            }
            set {
                this.operatorIdField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime VisitingTime {
            get {
                return this.visitingTimeField;
            }
            set {
                this.visitingTimeField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime LeaveTime {
            get {
                return this.leaveTimeField;
            }
            set {
                this.leaveTimeField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime ChatRequestTime {
            get {
                return this.chatRequestTimeField;
            }
            set {
                this.chatRequestTimeField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime ChatingTime {
            get {
                return this.chatingTimeField;
            }
            set {
                this.chatingTimeField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime WaitingDuring {
            get {
                return this.waitingDuringField;
            }
            set {
                this.waitingDuringField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime ChattingDuring {
            get {
                return this.chattingDuringField;
            }
            set {
                this.chattingDuringField = value;
            }
        }
        
        /// <remarks/>
        public int PageRequestCount {
            get {
                return this.pageRequestCountField;
            }
            set {
                this.pageRequestCountField = value;
            }
        }
        
        /// <remarks/>
        public string DomainRequested {
            get {
                return this.domainRequestedField;
            }
            set {
                this.domainRequestedField = value;
            }
        }
        
        /// <remarks/>
        public string PageRequested {
            get {
                return this.pageRequestedField;
            }
            set {
                this.pageRequestedField = value;
            }
        }
        
        /// <remarks/>
        public string Referrer {
            get {
                return this.referrerField;
            }
            set {
                this.referrerField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.1433")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.LiveSupport.cn/LiveSupportService/2009/04")]
    public enum VisitSessionStatus {
        
        /// <remarks/>
        Visiting,
        
        /// <remarks/>
        ChatRequesting,
        
        /// <remarks/>
        Chatting,
        
        /// <remarks/>
        Leave,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.1433")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.LiveSupport.cn/LiveSupportService/2009/04")]
    public partial class NewChangesCheckResult {
        
        private Operator[] operatorsField;
        
        private Visitor[] newVisitorsField;
        
        private VisitSession[] visitSessionChangeField;
        
        private Chat[] chatsField;
        
        private MessageCheckResult[] messagesField;
        
        private long newVisitorCheckTimeField;
        
        private ReturnCodeEnum returnCodeField;
        
        /// <remarks/>
        public Operator[] Operators {
            get {
                return this.operatorsField;
            }
            set {
                this.operatorsField = value;
            }
        }
        
        /// <remarks/>
        public Visitor[] NewVisitors {
            get {
                return this.newVisitorsField;
            }
            set {
                this.newVisitorsField = value;
            }
        }
        
        /// <remarks/>
        public VisitSession[] VisitSessionChange {
            get {
                return this.visitSessionChangeField;
            }
            set {
                this.visitSessionChangeField = value;
            }
        }
        
        /// <remarks/>
        public Chat[] Chats {
            get {
                return this.chatsField;
            }
            set {
                this.chatsField = value;
            }
        }
        
        /// <remarks/>
        public MessageCheckResult[] Messages {
            get {
                return this.messagesField;
            }
            set {
                this.messagesField = value;
            }
        }
        
        /// <remarks/>
        public long NewVisitorCheckTime {
            get {
                return this.newVisitorCheckTimeField;
            }
            set {
                this.newVisitorCheckTimeField = value;
            }
        }
        
        /// <remarks/>
        public ReturnCodeEnum ReturnCode {
            get {
                return this.returnCodeField;
            }
            set {
                this.returnCodeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.1433")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.LiveSupport.cn/LiveSupportService/2009/04")]
    public partial class Operator {
        
        private string operatorIdField;
        
        private string accountIdField;
        
        private string loginNameField;
        
        private string passwordField;
        
        private string nickNameField;
        
        private string emailField;
        
        private OperatorStatus statusField;
        
        private string operatorSessionField;
        
        private string aVChatStatusField;
        
        private bool isAdminField;
        
        private Department departmentField;
        
        private Account accountField;
        
        /// <remarks/>
        public string OperatorId {
            get {
                return this.operatorIdField;
            }
            set {
                this.operatorIdField = value;
            }
        }
        
        /// <remarks/>
        public string AccountId {
            get {
                return this.accountIdField;
            }
            set {
                this.accountIdField = value;
            }
        }
        
        /// <remarks/>
        public string LoginName {
            get {
                return this.loginNameField;
            }
            set {
                this.loginNameField = value;
            }
        }
        
        /// <remarks/>
        public string Password {
            get {
                return this.passwordField;
            }
            set {
                this.passwordField = value;
            }
        }
        
        /// <remarks/>
        public string NickName {
            get {
                return this.nickNameField;
            }
            set {
                this.nickNameField = value;
            }
        }
        
        /// <remarks/>
        public string Email {
            get {
                return this.emailField;
            }
            set {
                this.emailField = value;
            }
        }
        
        /// <remarks/>
        public OperatorStatus Status {
            get {
                return this.statusField;
            }
            set {
                this.statusField = value;
            }
        }
        
        /// <remarks/>
        public string OperatorSession {
            get {
                return this.operatorSessionField;
            }
            set {
                this.operatorSessionField = value;
            }
        }
        
        /// <remarks/>
        public string AVChatStatus {
            get {
                return this.aVChatStatusField;
            }
            set {
                this.aVChatStatusField = value;
            }
        }
        
        /// <remarks/>
        public bool IsAdmin {
            get {
                return this.isAdminField;
            }
            set {
                this.isAdminField = value;
            }
        }
        
        /// <remarks/>
        public Department Department {
            get {
                return this.departmentField;
            }
            set {
                this.departmentField = value;
            }
        }
        
        /// <remarks/>
        public Account Account {
            get {
                return this.accountField;
            }
            set {
                this.accountField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.1433")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.LiveSupport.cn/LiveSupportService/2009/04")]
    public enum OperatorStatus {
        
        /// <remarks/>
        Idle,
        
        /// <remarks/>
        InviteChat,
        
        /// <remarks/>
        Chatting,
        
        /// <remarks/>
        BeRightBack,
        
        /// <remarks/>
        Away,
        
        /// <remarks/>
        Offline,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.1433")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.LiveSupport.cn/LiveSupportService/2009/04")]
    public partial class Department {
        
        private string departmentIdField;
        
        private string departmentNameField;
        
        private Account accountField;
        
        private bool isDefaultField;
        
        private string addDateField;
        
        /// <remarks/>
        public string DepartmentId {
            get {
                return this.departmentIdField;
            }
            set {
                this.departmentIdField = value;
            }
        }
        
        /// <remarks/>
        public string DepartmentName {
            get {
                return this.departmentNameField;
            }
            set {
                this.departmentNameField = value;
            }
        }
        
        /// <remarks/>
        public Account Account {
            get {
                return this.accountField;
            }
            set {
                this.accountField = value;
            }
        }
        
        /// <remarks/>
        public bool IsDefault {
            get {
                return this.isDefaultField;
            }
            set {
                this.isDefaultField = value;
            }
        }
        
        /// <remarks/>
        public string AddDate {
            get {
                return this.addDateField;
            }
            set {
                this.addDateField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.1433")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.LiveSupport.cn/LiveSupportService/2009/04")]
    public partial class Account {
        
        private string accountIdField;
        
        private string accountNumberField;
        
        private string companyNameField;
        
        private string industryField;
        
        private string emailField;
        
        private string contactNameField;
        
        private string phoneField;
        
        private string urlField;
        
        private string domainField;
        
        private int operatorCountField;
        
        private string provinceField;
        
        private string cityField;
        
        private System.DateTime registerDateField;
        
        private string remarkField;
        
        private string paymentIdField;
        
        /// <remarks/>
        public string AccountId {
            get {
                return this.accountIdField;
            }
            set {
                this.accountIdField = value;
            }
        }
        
        /// <remarks/>
        public string AccountNumber {
            get {
                return this.accountNumberField;
            }
            set {
                this.accountNumberField = value;
            }
        }
        
        /// <remarks/>
        public string CompanyName {
            get {
                return this.companyNameField;
            }
            set {
                this.companyNameField = value;
            }
        }
        
        /// <remarks/>
        public string Industry {
            get {
                return this.industryField;
            }
            set {
                this.industryField = value;
            }
        }
        
        /// <remarks/>
        public string Email {
            get {
                return this.emailField;
            }
            set {
                this.emailField = value;
            }
        }
        
        /// <remarks/>
        public string ContactName {
            get {
                return this.contactNameField;
            }
            set {
                this.contactNameField = value;
            }
        }
        
        /// <remarks/>
        public string Phone {
            get {
                return this.phoneField;
            }
            set {
                this.phoneField = value;
            }
        }
        
        /// <remarks/>
        public string Url {
            get {
                return this.urlField;
            }
            set {
                this.urlField = value;
            }
        }
        
        /// <remarks/>
        public string Domain {
            get {
                return this.domainField;
            }
            set {
                this.domainField = value;
            }
        }
        
        /// <remarks/>
        public int OperatorCount {
            get {
                return this.operatorCountField;
            }
            set {
                this.operatorCountField = value;
            }
        }
        
        /// <remarks/>
        public string Province {
            get {
                return this.provinceField;
            }
            set {
                this.provinceField = value;
            }
        }
        
        /// <remarks/>
        public string City {
            get {
                return this.cityField;
            }
            set {
                this.cityField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime RegisterDate {
            get {
                return this.registerDateField;
            }
            set {
                this.registerDateField = value;
            }
        }
        
        /// <remarks/>
        public string Remark {
            get {
                return this.remarkField;
            }
            set {
                this.remarkField = value;
            }
        }
        
        /// <remarks/>
        public string PaymentId {
            get {
                return this.paymentIdField;
            }
            set {
                this.paymentIdField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.1433")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.LiveSupport.cn/LiveSupportService/2009/04")]
    public partial class Visitor {
        
        private string visitorIdField;
        
        private string accountIdField;
        
        private string nameField;
        
        private string emailField;
        
        private int visitCountField;
        
        private string companyField;
        
        private string remarkField;
        
        private bool isVIPField;
        
        private VisitSession currentSessionField;
        
        /// <remarks/>
        public string VisitorId {
            get {
                return this.visitorIdField;
            }
            set {
                this.visitorIdField = value;
            }
        }
        
        /// <remarks/>
        public string AccountId {
            get {
                return this.accountIdField;
            }
            set {
                this.accountIdField = value;
            }
        }
        
        /// <remarks/>
        public string Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        public string Email {
            get {
                return this.emailField;
            }
            set {
                this.emailField = value;
            }
        }
        
        /// <remarks/>
        public int VisitCount {
            get {
                return this.visitCountField;
            }
            set {
                this.visitCountField = value;
            }
        }
        
        /// <remarks/>
        public string Company {
            get {
                return this.companyField;
            }
            set {
                this.companyField = value;
            }
        }
        
        /// <remarks/>
        public string Remark {
            get {
                return this.remarkField;
            }
            set {
                this.remarkField = value;
            }
        }
        
        /// <remarks/>
        public bool IsVIP {
            get {
                return this.isVIPField;
            }
            set {
                this.isVIPField = value;
            }
        }
        
        /// <remarks/>
        public VisitSession CurrentSession {
            get {
                return this.currentSessionField;
            }
            set {
                this.currentSessionField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.1433")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.LiveSupport.cn/LiveSupportService/2009/04")]
    public enum ReturnCodeEnum {
        
        /// <remarks/>
        ReturnCode_Success,
        
        /// <remarks/>
        ReturnCode_SessionInvalid,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.1433")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.LiveSupport.cn/LiveSupportService/2009/04")]
    public partial class MessageCheck {
        
        private string chatIdField;
        
        private long lastCheckTimeField;
        
        /// <remarks/>
        public string ChatId {
            get {
                return this.chatIdField;
            }
            set {
                this.chatIdField = value;
            }
        }
        
        /// <remarks/>
        public long LastCheckTime {
            get {
                return this.lastCheckTimeField;
            }
            set {
                this.lastCheckTimeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.1433")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.LiveSupport.cn/LiveSupportService/2009/04")]
    public partial class NewChangesCheck {
        
        private MessageCheck[] chatSessionChecksField;
        
        private long newVisitorLastCheckTimeField;
        
        /// <remarks/>
        public MessageCheck[] ChatSessionChecks {
            get {
                return this.chatSessionChecksField;
            }
            set {
                this.chatSessionChecksField = value;
            }
        }
        
        /// <remarks/>
        public long NewVisitorLastCheckTime {
            get {
                return this.newVisitorLastCheckTimeField;
            }
            set {
                this.newVisitorLastCheckTimeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.1433")]
    public delegate void LoginCompletedEventHandler(object sender, LoginCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.1433")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class LoginCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal LoginCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Operator Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Operator)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.1433")]
    public delegate void LogoutCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.1433")]
    public delegate void GetAllVisitorsCompletedEventHandler(object sender, GetAllVisitorsCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.1433")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetAllVisitorsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetAllVisitorsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Visitor[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Visitor[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.1433")]
    public delegate void CheckNewChangesCompletedEventHandler(object sender, CheckNewChangesCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.1433")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class CheckNewChangesCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal CheckNewChangesCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public NewChangesCheckResult Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((NewChangesCheckResult)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.1433")]
    public delegate void IsTypingCompletedEventHandler(object sender, IsTypingCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.1433")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class IsTypingCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal IsTypingCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.1433")]
    public delegate void SendFileCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.1433")]
    public delegate void UploadFileCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.1433")]
    public delegate void SendMessageCompletedEventHandler(object sender, SendMessageCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.1433")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class SendMessageCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal SendMessageCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.1433")]
    public delegate void ChangePasswordCompletedEventHandler(object sender, ChangePasswordCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.1433")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ChangePasswordCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ChangePasswordCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public int Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((int)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.1433")]
    public delegate void ResetOperatorPasswordCompletedEventHandler(object sender, ResetOperatorPasswordCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.1433")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ResetOperatorPasswordCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ResetOperatorPasswordCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public int Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((int)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.1433")]
    public delegate void CloseChatCompletedEventHandler(object sender, CloseChatCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.1433")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class CloseChatCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal CloseChatCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.1433")]
    public delegate void GetHistoryChatMessageCompletedEventHandler(object sender, GetHistoryChatMessageCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.1433")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetHistoryChatMessageCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetHistoryChatMessageCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Message[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Message[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.1433")]
    public delegate void GetHistoryPageRequestsCompletedEventHandler(object sender, GetHistoryPageRequestsCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.1433")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetHistoryPageRequestsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetHistoryPageRequestsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public PageRequest[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((PageRequest[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.1433")]
    public delegate void AcceptChatRequestCompletedEventHandler(object sender, AcceptChatRequestCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.1433")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class AcceptChatRequestCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal AcceptChatRequestCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public int Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((int)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.1433")]
    public delegate void InviteChatCompletedEventHandler(object sender, InviteChatCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.1433")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class InviteChatCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal InviteChatCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Chat Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Chat)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.1433")]
    public delegate void GetSystemAdvertiseCompletedEventHandler(object sender, GetSystemAdvertiseCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.1433")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetSystemAdvertiseCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetSystemAdvertiseCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public SystemAdvertise[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((SystemAdvertise[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.1433")]
    public delegate void SaveQuickResponseCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.1433")]
    public delegate void GetQuickResponseCompletedEventHandler(object sender, GetQuickResponseCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.1433")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetQuickResponseCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetQuickResponseCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public QuickResponseCategory[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((QuickResponseCategory[])(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591