Ext.MyGrid=Ext.extend(Ext.grid.GridPanel ,{
xtype:"grid",
	title:"预定管理",
	store:{
		xtype:"jsonstore",
		autoLoad:true
	},
	width:792,
	height:560,
	columns:[
		{
			header:"编号",
			sortable:true,
			resizable:true,
			dataIndex:"data1",
			width:100
		},
		{
			header:"编码",
			sortable:true,
			resizable:true,
			dataIndex:"data2",
			width:100
		},
		{
			header:"预定客户名称",
			sortable:true,
			resizable:true,
			dataIndex:"data3",
			width:100
		},
		{
			header:"所属工业园",
			sortable:true,
			resizable:true,
			dataIndex:"",
			width:100
		},
		{
			header:"所属房产",
			sortable:true,
			resizable:true,
			dataIndex:"",
			width:100
		},
		{
			header:"预定时间",
			sortable:true,
			resizable:true,
			dataIndex:"",
			width:100
		},
		{
			header:"操作时间",
			sortable:true,
			resizable:true,
			dataIndex:"",
			width:100,
			format:"m/d/Y"
		}
	],
	initComponent: function(){
		this.tbar=[
			{
				text:"新增"
			},
			{
				text:"修改"
			},
			{
				text:"删除"
			},
			{
				xtype:"label",
				text:""
			},
			{
				xtype:"textfield",
				fieldLabel:"标签"
			},
			{
				text:"搜索"
			}
		]
		Ext.MyGrid.superclass.initComponent.call(this);
	}
})